version: 2
jobs:
  lint_test_cov:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

      - run: npm run lint

      - run: npm test

      - run: npm run codecov

  build_publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}

      - run: npm run build

      - run:
          name: Publish to NPM
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            npm publish

workflows:
  version: 2
  test_build:
    jobs:
      - lint_test_cov
      - build_publish:
          requires:
            - lint_test_cov
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-\w+\.[0-9]+)?$/
