version: 2
jobs:
  test_build_publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.14
    steps:
      - checkout

      - run:
          name: Install
          command: npm install

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Test
          command: npm test

      - run:
          name: Build
          command: npm run build

      - run:
          name: Publish to NPM
          command: npm publish

workflows:
  version: 2
  build:
    jobs:
      - test_build_publish:
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-\w+\.[0-9]+)?$/
